FROM ruby:3.3.0
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
RUN apt-get update -qq && apt-get install -y libpq-dev nodejs
WORKDIR /app
RUN echo pwd
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
CMD ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]